"use client";

export default function Reserve(){
    return( 
    <div className="flex-grow">
        Pagina de reservas
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
        <div>Hola hola</div>
    </div>
    );
}